import { ThemeProvider } from "@/context/ThemeProvider";
import "./globals.css";
import { Metadata } from 'next';
import { Poppins } from 'next/font/google';

const poppins = Poppins({
  weight: ['400', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} font-sans antialiased`}>
        <ThemeProvider defaultTheme="system" storageKey="sankofa-theme">{children}</ThemeProvider>
      </body>
    </html>
  );
}