import { ThemeProvider } from "@/context/ThemeProvider";
import "./globals.css";
import { Metadata } from 'next';
import localFont from 'next/font/local'; // Use localFont for custom fonts
import { QueryProvider } from "@/context/QueryProvider";
import Footer from "@/components/footer/footer";
import Navbar from "@/components/navbar/navbar";

// Define the local Poppins font
const poppins = localFont({
  src: [
    {
      path: '../../public/fonts/Poppins-Regular.ttf', // Path to .ttf file
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Poppins-Bold.ttf', // Path to .ttf file
      weight: '700',
      style: 'normal',
    },
  ],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  const theme = localStorage.getItem('sankofa-theme') || 'system';
                  if (theme === 'system') {
                    const systemTheme = window.matchMedia('(prefers-color-scheme: dark)').matches
                      ? 'dark'
                      : 'light';
                    document.documentElement.classList.add(systemTheme);
                  } else {
                    document.documentElement.classList.add(theme);
                  }
                } catch (e) {}
              })();
            `,
          }}
        />
      </head>
      <body className={`${poppins.className} font-sans antialiased`}>
        <ThemeProvider defaultTheme="system" storageKey="sankofa-theme">
          <QueryProvider>
            <Navbar />
            {children}
            <Footer />
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
