import { ThemeProvider } from "@/context/ThemeProvider";
import "./globals.css";
import { Metadata } from 'next';
import localFont from 'next/font/local'; // Use localFont for custom fonts
import { QueryProvider } from "@/context/QueryProvider";

// Define the local Poppins font
const poppins = localFont({
  src: [
    {
      path: '../../public/fonts/Poppins-Regular.ttf', // Path to .ttf file
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Poppins-Bold.ttf', // Path to .ttf file
      weight: '700',
      style: 'normal',
    },
  ],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} font-sans antialiased`}>
        <ThemeProvider defaultTheme="system" storageKey="sankofa-theme">
          <QueryProvider>
            {children}
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}